---

- hosts: all
  become: true
  pre_tasks:

  - name: update packages cache (RedHat Servers)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: update packages cache (Debian Servers)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]


- hosts: all
  become: true
  tasks:

  - name: add ssh key for sim0ne
    tags: always
    authorized_key:
      user: sim0ne
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOW97fiDI4P0K7K9pwfj8PMzJmHPxByiOEDiY0kvad2j ansible"
  

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
        src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: start apache (Debian Servers)
    tags: apache,apache2,debian
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644



  - name: install httpd and php packages for Red Hat Servers
    tags: apache,centos,fedora,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: start httpd (Red Hat Servers)
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ["Fedora", "CentOS"]

  - name: change email address for admin in fedora
    tags: apache,fedora,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin someone@somewhere.net
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: restart httpd (Fedora Linux)
    tags: apache,httpd,fedora
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package for Red Hat Servers
    tags: fedora,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: install mariadb package for Debian Servers
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest


