- name: install httpd and php packages for Red Hat Servers
  tags: apache,centos,fedora,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution in ["CentOS", "Fedora"]

- name: start httpd (Red Hat Servers)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["Fedora", "CentOS"]

- name: change email address for admin in fedora
  tags: apache,fedora,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin someone@somewhere.net
  when: ansible_distribution == "Fedora"
  register: httpd

- name: restart httpd (Fedora Linux)
  tags: apache,httpd,fedora
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: install apache and php packages for Ubuntu Servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: start apache (Debian Servers)
  tags: apache,apache2,debian
  service:
      name: apache2
      state: started
  when: ansible_distribution == "Ubuntu"

- name: copy default html file for site
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
